org: org1
space: development
space-developer:
  ldap_users: []
  users: []
  ldap_group: "test_space1_auditors"
space-manager:
  ldap_users: []
  users: []
  ldap_group: "test_space1_managers"
space-auditor:
  ldap_users: []
  users: []
  ldap_group: "test_space1_auditors"
allow-ssh: false
enable-space-quota: false
memory-limit: 10240
instance-memory-limit: -1
total-routes: 10
total-services: -1
paid-service-plans-allowed: true
enable-security-group: false
